tech = ["tsmc65", "tsmc28", "tower180"]

[defaults.nmos]
w = [1]
l = [1]
nf = [1]
type = ["lvt"]

[defaults.pmos]
w = [1]
l = [1]
nf = [1]
type = ["lvt"]

[[sweeps]]
devices = ["MP"]
w = [5, 10, 20, 40]
l = [1, 2]
